### PR TITLE
Fix test run errors and cleanup files sfter test run

### LINKED ISSUE #754: Cleanup resources created during the cellery test command failure
Cleanup .ballerina and ballerina.toml files which have got created during the cellery test command after that execution. And this should be cleaned up regardless of success/failure of cellery run.

### LINKED ISSUE #763: Cannot run ballerina inline tests defined with cellery test
Steps to execute: Run  `cellery test wso2cellery/pet-be-cell:latest-dev -n pet-be`
 
Below error was the log. 
```
Log:
Log: -------------------------------------------------------
Log:  T E S T S
Log: -------------------------------------------------------
Log: Running io.cellery.test.petstore.be.PetBeTest
Log: Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@694f9431
Log: Request executed: POST http://pet-be--gateway-service:80/controller/orders HTTP/1.1
Log: Response received: HttpResponseProxy{HTTP/1.1 200 OK [x-powered-by: Express, content-type: application/json; charset=utf-8, content-length: 36, etag: W/"24-G+OXgLEbU9bvp9DVsLRJH1cvKos", date: Wed, 02 Oct 2019 10:26:03 GMT, x-envoy-upstream-service-time: 3244, server: envoy] ResponseEntityProxy{[Content-Type: application/json; charset=utf-8,Content-Length: 36,Chunked: false]}}
Log: Response: {"status":"SUCCESS","data":{"id":0}}
Log: Request executed: GET http://pet-be--gateway-service:80/controller/orders HTTP/1.1
Log: Response received: HttpResponseProxy{HTTP/1.1 200 OK [x-powered-by: Express, content-type: application/json; charset=utf-8, content-length: 328, etag: W/"148-LeEKG81lq6u0qT/9zqoERCuOT6s", date: Wed, 02 Oct 2019 10:26:04 GMT, x-envoy-upstream-service-time: 950, server: envoy] ResponseEntityProxy{[Content-Type: application/json; charset=utf-8,Content-Length: 328,Chunked: false]}}
Log: Response: {"status":"SUCCESS","data":{"orders":[{"order":[{"item":{"id":1,"name":"Pet Travel Carrier Cage","description":"Ideal for airline travel, the carry cage has a sturdy handle grip and tie down strapping points for safe and secure travel","unitPrice":50,"inStock":100},"amount":1}],"customer":"","id":1,"orderDate":"02-10-2019"}]}}
Log: Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.545 sec
Log:
Log: Results :
Log:
Log: Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
Log:
Log: [INFO] ------------------------------------------------------------------------
Log: [INFO] BUILD SUCCESS
Log: [INFO] ------------------------------------------------------------------------
Log: [INFO] Total time: 02:28 min
Log: [INFO] Finished at: 2019-10-02T10:26:05Z
Log: [INFO] ------------------------------------------------------------------------
Info: Waiting for test job to complete...
Warning: Error getting status of job pet-be-test--pet-be-test-job. Skipping collection of logs.
Info: Deleting test cell pet-be-test
Info: Ballerina project initialized
Info: Compiling tests
Info:     sinthuja/pet-be:0.0.1
Warning: error:sinthuja/pet-be:0.0.1::tests/pet-be-test.bal:29:45: undefined function 'run'
Info: Deleting pet-be instance...
T: Your process has exited.
T: Exit cleanup in progress


✔ Completed running tests for instance pet-be

```

As you can see there are few issues though maven tests were executed.

1) The logs of the tests were not retrieved. - Warning: Error getting status of job pet-be-test--pet-be-test-job. Skipping collection of logs.
2) Celelry inline tests wasn't executed
3) Inline tests wasn't executed. And it compiles  sinthuja/pet-be:0.0.1? My image name is 'wso2cellery/pet-be-cell:latest-dev'

### PR DESCRIPTION
**Pull request by azinneera**

### CODE REVIEW

File: components/cli/pkg/commands/test.go [hunk 1]
```diff
@@ -180,6 +180,9 @@ func RunTest(cellImageTag string, instanceName string, startDependencies bool, s
 	if err != nil {
 		util.ExitWithErrorMessage("Failed to test Cell instance"+instanceName, err)
 	}
+	//Remove Ballerina toml and local repo to avoid failing cellery build and run
+	os.Remove(constants.BALLERINA_TOML)
+	os.RemoveAll(constants.BALLERINA_LOCAL_REPO)
```
Comment (sinthuja) [inline components/cli/pkg/commands/test.go]: Do we need to check whether the .ballerina is created by cellery test before we delete it? Because there is .ballerina in the home directory as well, so I think we are not supposed to delete that directory. We only have to delete the .ballerina folder created during the test execution.

Comment (sinthuja) [reply components/cli/pkg/commands/test.go]: Btw, is this directories are getting created in the tmp location? Not in directory where the command is executed?

Comment (azinneera) [reply components/cli/pkg/commands/test.go]: A target folder is created in the pwd for running tests. So it will clean the .ballerina and Ballerina toml that is in the pwd/targed directory

Comment (sinthuja) [reply components/cli/pkg/commands/test.go]: Ok, I somehow experienced a situation where .ballerina was created in pwd, not in pwd/target. If it's creating to pwd/target, then it's safe to add this fix.
