### PR TITLE
Avoid starting telepresence when tests not found

### LINKED ISSUE #937: cellery test creates telepresence pods even if there are no tests and also does not cleanup
**Description:**
`cellery test` command creates telepresence pods even if there are no tests present. Also it does not seem to cleanup afterwards. This needs to be improved.

**Affected Product Version:**
0.5.0

### LINKED ISSUE #949: Cellery test fails for instance name 'test'
**Description:**
Cellery test fails when I run the `cellery test` command with the instance name 'test'.

```
$ cellery test madusha/foo:0.5 -n test                                                                              

✔ Extracting cell image
✔ Creating telepresence k8s resources
T: How Telepresence uses sudo: https://www.telepresence.io/reference/install#dependencies
T: Invoking sudo. Please enter your sudo password.
Password:
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud
T: hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using the existing proxy Deployment telepresence--telepresence-deployment

T: No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

T: Mounting remote volumes failed, they will be unavailable in this session. If you are running on Windows Subystem for Linux then see https://github.com/datawire/telepresence/issues/115, otherwise please
T: report a bug, attaching telepresence.log to the bug report: https://github.com/datawire/telepresence/issues/new

T: Mount error was: mount_osxfuse: the file system is not available (1)
T: Setup complete. Launching your command.
Compiling source
	madushagunasekara/test:0.1.0
error: madushagunasekara/test:0.1.0::tests/foo_test.bal:2:1: cannot resolve module 'ballerina/test'
error: madushagunasekara/test:0.1.0::tests/foo_test.bal:9:1: undefined module 'test'
error: madushagunasekara/test:0.1.0::tests/foo_test.bal:9:1: undefined annotation 'BeforeSuite'
error: madushagunasekara/test:0.1.0::tests/foo_test.bal:25:1: undefined module 'test'
error: madushagunasekara/test:0.1.0::tests/foo_test.bal:25:1: undefined annotation 'Config'
error: madushagunasekara/test:0.1.0::tests/foo_test.bal:28:5: undefined module 'test'
error: madushagunasekara/test:0.1.0::tests/foo_test.bal:28:5: undefined function 'assertTrue'
error: madushagunasekara/test:0.1.0::tests/foo_test.bal:32:1: undefined module 'test'
error: madushagunasekara/test:0.1.0::tests/foo_test.bal:32:1: undefined annotation 'AfterSuite'
T: Your process exited with return code 1.
T: Exit cleanup in progress

T: Telepresence 0.103 is available (you're running 0.101). https://www.telepresence.io/reference/changelog


Cellery test command failed: failed to test Cell instance test, failed to run bal file, error occurred while waiting for tests to complete, exit status 1
```

**Steps to reproduce:**

1. Run `cellery init foo`
2. Run `cellery init test foo/foo.bal`
3. Run `cellery build foo_proj/src/foo/foo.bal madusha/foo:0.5`
4. Run `cellery test madusha/foo:0.5 -n test`

### PR DESCRIPTION
**Pull request by azinneera**

### CODE REVIEW

File: components/cli/pkg/commands/image/test.go [hunk 1]
```diff
@@ -38,17 +37,18 @@ import (
 	"github.com/cellery-io/sdk/components/cli/pkg/image"
 	"github.com/cellery-io/sdk/components/cli/pkg/kubernetes"
 	"github.com/cellery-io/sdk/components/cli/pkg/util"
-	"github.com/cellery-io/sdk/components/cli/pkg/version"
 )
 
+const celleryVerboseMode = "DEBUG_MODE"
```
[the remark this answers is not in the document]
Comment (azinneera) [reply components/cli/pkg/commands/image/test.go]: Fixed with 16a167d

File: components/cli/pkg/commands/image/test.go [hunk 2]
```diff
@@ -275,7 +274,7 @@ func startTestCellInstance(cli cli.Cli, imageDir string, instanceName string, ru
 	} else {
 		var balModule string
 
-		if instanceName != "" {
+		if instanceName != "" && instanceName != "test" {
```
Comment (madushajg) [inline components/cli/pkg/commands/image/test.go]: Don't we need to inform the user that the name "test" can't use as an instance name?

Comment (azinneera) [reply components/cli/pkg/commands/image/test.go]: No since this is only used for the name of the ballerina module to extract and run the tests which is an implementation detail. The user still can create an intance named "test".

Comment (nadundesilva) [reply components/cli/pkg/commands/image/test.go]: We would have similar issues for all keywords and already existing package names in ballerina right ? Not just `test`

Comment (azinneera) [reply components/cli/pkg/commands/image/test.go]: Yes, that should be handled by Ballerina. Created an issue to track this.
https://github.com/ballerina-platform/ballerina-lang/issues/19997
